version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:  > 
      sh -c "python manage.py runserver 0.0.0.0:8000"
    enviroment: # In the real world these should obvoiously not be hard coded in it is important that 
                # DB_NAME is equal to POSTGRES_USER DB_USER is equal to POSTGRES_USER and DB_PASS is equal to 
                # POSTGRES_PASSWORD
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    enviroment: # in the real world use real user name and password not one which is hard coded in
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:
